# Generated by Django 6.0.3 on 2026-04-21 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('uzbekiston', "O'zbekiston"), ('jahon', 'Jahon'), ('iqtisodiyot', 'Iqtisodiyot'), ('sport', 'Sport'), ('texnologiya', 'Texnologiya')], default='uzbekiston', max_length=30),
        ),
    ]
